task_name: 'HydropsOTO'

# data
data_root: 'DATA ROOT PATH'
dataset: 'OTO'
mrc_src_path: 'magnetic resonan cisternography (MRC) DATA PATH '
mi2_src_path: 'HYDROPS-Mi2 DATA PATH'
expresult_path: './exp' #'RESULT PATH'

checkpoint_path: './exp/checkpoint' #'CHECKPOINT PATH'
log_path: ./log' #'LOG PATH'
classes: 2
modality: MRI
len_dataset: 50000 

# model
architecture: 3DU-Net
in_chan: 2 
base_chan: 16 
down_scale: [[1,2,2], [2,2,2], [2,2,2], [2,2,2]]
kernel_size: [[1,3,3], [2,3,3], [3,3,3], [3,3,3], [3,3,3]]
block: SingleConv
norm: in

# train
start_epoch: 0
num_epochs: 100
val_freq: 50
iter_per_epoch: 200
batch_size: 4
training_size: [24, 64, 64] 
num_workers: 4 
aug_device: 'cpu'
random_seed: 2024
split_seed: 0
k_fold: 5 
optimizer: adamw
base_lr: 0.001
betas: [0.9, 0.999]
weight_decay: 0.05  
weight: [0.5, 1, 1, 1] 
scale: [0.1, 0.3, 0.3]  
rotate: [30, 0, 0]  
translate: [0, 0, 0]
gaussian_noise_std: 0.02
additive_brightness_std: 0.7 
gamma_range: [0.5, 1.6]
print_freq: 5
torch_compile: False

# validation 
val_freq: 10 
spacing: [1.0, 0.5, 0.5]

# inference
sliding_window: True
window_size: [24, 64, 64]
