# datasets
task_name: 'HydropsOTO'
data_root: 'DATA ROOT PATH'
mrc_src_path: 'magnetic resonan cisternography (MRC) DATA PATH '
mi2_src_path: 'HYDROPS-Mi2 DATA PATH'
expresult_path: 'RESULT PATH'
checkpoint_path: 'CHECKPOINT PATH'
log_path: 'LOG PATH'
classes: 2
modality: MRI

# model
architecture: 3DU-Net
in_chan: 2 
base_chan: 16 
down_scale: [[1,2,2], [2,2,2], [2,2,2], [2,2,2]]
kernel_size: [[1,3,3], [2,3,3], [3,3,3], [3,3,3], [3,3,3]]
block: SingleConv
norm: in

# train
start_epoch: 1
num_epochs: 100
batch_size: 4
training_size: [24, 64, 64] 
num_workers: batch_size * 4 
aug_device: 'cpu'
seed: 2024
k_fold: 5 
optimizer: adamw
base_lr: 1e-3
betas: [0.9, 0.999]
weight_decay: 0.05  
weight: [0.5, 1, 1, 1] 
scale: [0.1, 0.3, 0.3]  
rotate: [30, 0, 0]  
translate: [0, 0, 0]
gaussian_noise_std: 0.02
additive_brightness_std: 0.7 
gamma_range: [0.5, 1.6]
print_freq: 5
iter_per_epoch: 200

# validation 
ema: True
ema_alpha: 0.99
val_freq: 10 
spacing: [1.0, 0.5, 0.5]

# inference
sliding_window: True
window_size: [24, 64, 64]
